// This file is generated by CMake. Do not edit it manually.
#pragma once
#include <string>
#include <unordered_map>
#include "Resource.hpp"

LOAD_RESOURCE(cash_wav);
LOAD_RESOURCE(cash_register_sound_wav);
LOAD_RESOURCE(celestial_off_wav);
LOAD_RESOURCE(celestial_on_wav);
LOAD_RESOURCE(fard_wav);
LOAD_RESOURCE(fonts_Comfortaa_Bold_ttf);
LOAD_RESOURCE(fonts_Comfortaa_ttf);
LOAD_RESOURCE(fonts_Mojangles_Bold_ttf);
LOAD_RESOURCE(fonts_Mojangles_ttf);
LOAD_RESOURCE(fonts_Open_Sans_Bold_ttf);
LOAD_RESOURCE(fonts_Open_Sans_ttf);
LOAD_RESOURCE(fonts_Product_Sans_Bold_ttf);
LOAD_RESOURCE(fonts_Product_Sans_ttf);
LOAD_RESOURCE(fonts_SF_Pro_Display_Bold_ttf);
LOAD_RESOURCE(fonts_SF_Pro_Display_ttf);
LOAD_RESOURCE(fonts_Sarabun_Light_ttf);
LOAD_RESOURCE(fonts_Tenacity_Icons_ttf);
LOAD_RESOURCE(mariodeath_wav);
LOAD_RESOURCE(notch_png);
LOAD_RESOURCE(nursultan_off_wav);
LOAD_RESOURCE(nursultan_on_wav);
LOAD_RESOURCE(seven_days_png);
LOAD_RESOURCE(skinblinker_txt);
LOAD_RESOURCE(smooth_off_wav);
LOAD_RESOURCE(smooth_on_wav);
LOAD_RESOURCE(windows_background_wav);
LOAD_RESOURCE(yo_at_here_gif);

class ResourceLoader {
public:
    static inline std::unordered_map<std::string, Resource> Resources;
    static void loadResources();
};
